apiVersion: apps/v1
kind: Deployment
metadata:
  name: ids-wakeup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ids-wakeup
  template:
    metadata:
      labels:
        app: ids-wakeup
    spec:
      containers:
      - name: ids-wakeup
        image: docker.io/greavr/ids-wakeup
        imagePullPolicy: Always
        env:
          - name: TARGET_IP
            value: "10.0.0.2"
        resources:
          limits:
            memory: 128Mi
            cpu: 500m